# Generated by Django 5.0.6 on 2024-05-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_Recuerdame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='is_taken',
        ),
    ]
